<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BLRL5CG0287TTQ" ignored="0" name="ProductInfo Test" tests="2" failures="2" timestamp="2022-01-31T00:26:51 IST" time="11.324" errors="0">
  <testcase name="productImagesTest" time="1.847" classname="com.qa.OpenCart.Tests.ProductInfoTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [0]
at com.qa.OpenCart.Tests.ProductInfoTest.productImagesTest(ProductInfoTest.java:23)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- productImagesTest -->
  <testcase name="verifyproductInfoTest_MacBook" time="1.69" classname="com.qa.OpenCart.Tests.ProductInfoTest">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.qa.OpenCart.Pages.ProductInfoPage.getProductInfo(ProductInfoPage.java:63)
at com.qa.OpenCart.Tests.ProductInfoTest.verifyproductInfoTest_MacBook(ProductInfoTest.java:31)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- verifyproductInfoTest_MacBook -->
</testsuite> <!-- ProductInfo Test -->
